### ISSUE TITLE
Centos compatibility

### ISSUE THREAD

**Issue by willrnch** [Nanocloud/community#187]
Known issues:
Building nanocloud on Centos is not possible because:
- netcat package doesn't support -z option
- `netcat` binary doesn't exist. Only `nc`
- qemu binary location differ (`/usr/libexec/qemu-kvm` instead of `/usr/bin/qemu-system-x86_64`)

Other:
To install sshpass: `yum --enablerepo=epel -y install sshpass`

**Comment by bruceadowns** [comment]
Which version(s) of centos are supported?

Which version(s) of centos does this bug affect?

**Comment by willrnch** [comment]
This as been spotted on CentOS 7. No other version has been tested so far.

**Comment by domrod** [comment]
Here are some tricks to run Nanocloud without modification on Centos 7.2

Use **epel** repo for sshpass and qemu:
$ yum install -y epel-release

For **sshpass** (as already described by Costent):
$ yum --enablerepo=epel -y install sshpass

For **QEMU**:
$ yum --enablerepo=epel -y install qemu-system-x86.x86_64
$ yum --enablerepo=epel -y install qemu-img
$ yum install -y seabios-bin

Use rpmforge repo for **netcat** (cryptcat version):
$ rpm -Uvh http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el7.rf.x86_64.rpm
$ yum install -y cryptcat 
$ ln -s /usr/bin/cryptcat /usr/local/bin/nc
$ ln -s /usr/bin/cryptcat /usr/local/bin/netcat
