### ISSUE TITLE
Docker disk space is limited to 10GB

### ISSUE THREAD

**Issue by Gentux** [Nanocloud/community#299]
Disk space in _iaas_ container is limited and forbids a normal use of windows machine:

`
$ docker exec -it iaas-module bash
root@1d5628b46736:/var/lib/nanocloud/images# df -h
Filesystem                                                                                       Size  Used Avail Use% Mounted on

/dev/mapper/docker-0:166-62386-6709ff264be58525bc7be5a096e7d40d94a3829c4448d60b2d1f020f03bbc24  9.8G  9.8G     0 100% /

tmpfs                                                                                             16G     0   16G   0% /dev

tmpfs                                                                                             16G     0   16G   0% /sys/fs/cgroup

overlay                                                                                          1.8T  209G  1.5T  13% /etc/hosts

shm
`

As Windows image is provisioned with a 30Go disk, I suggest this limit should be at least 30Go.

**Comment by domrod** [comment]
The problem occurs in a special configuration :

CoreOS (baremetal) with overlayFS -> Debian Container -> Docker with devicemapper -> Nanocloud

About CoreOS:
CoreOS alpha (962.0.0)
Docker 1.10.1
Storage Driver: overlay

In the case of a Nested VM on Openstack, there is no limitation.
