### ISSUE TITLE
No live refresh on dashboard

### ISSUE THREAD

**Issue by tanguybernard** [Nanocloud/community#542]
If I publish an application, and then go back to the dashboard, there is 0 application. If I refresh, there is 1.

**Comment by domrod** [comment]
Thanks to point out this behavior Tanguy.

Dashboard is currently being improved on our last sprints. Our QA has also noted this to be changed to have a live display.

Could you by the way precise the version tested (stable with release number or master under development)?

Thanks for your involvement in Nanocloud Community.

**Comment by tanguybernard** [comment]
Okay, thanks.

Yes: 0.6.0rc1
