### ISSUE TITLE
Refresh any pages goes back to the dashboard

### ISSUE THREAD

**Issue by tanguybernard** [Nanocloud/community#543]
For example, when I refresh "Machines" page, I go back to the dashboard.

**Comment by domrod** [comment]
Yes, this the current normal behavior. 

Refreshing the web portal redirects you to the default page which is the Dashboard page.

Any page (Machines, Applications, Users) should not need to be refreshed to have the real time information, as you can see for instance in Users' list  when you create a new user.

We currently work to have an improved live display on all pages that does not need to refresh the browser.

Thanks for your involvement in Nanocloud Community and stay tuned.

**Comment by dynamiccast** [comment]
Hi,

@domrod This is not actually a normal behavior and was confirmed as a bug by our frontend developer @spacewoox.
I do agree however that we sould have as much as live refreshed information as possible.

**Comment by dynamiccast** [comment]
Fixed in https://github.com/Nanocloud/community/issues/543
