### ISSUE TITLE
Windows VM Network Communication with physical LAN

### ISSUE THREAD

**Issue by nayanivijay26** [Nanocloud/community#691]
Hi All,

Really i impress with nanocloud its performance is robust.

I want to know how to communication Windows os vm with physical network. i want map my NAS as share drive. 

I am not able to ping from windows to my physical network.

Thanks,

Vijay Nayani

**Comment by nayanivijay26** [comment]
Any Update ?

**Comment by dynamiccast** [comment]
Hi,

This repository has been deprecated as we upgraded to Nanocloud 2.0. 

https://github.com/Nanocloud/nanocloud 

As for your virtual machine. You NAS should be accessible from your virtual machine like any device from your local network. Please upgrade to 2.0 and let us know if you still experience any issue.
